import React, { useState } from 'react';

const LegalAgreementModal = ({ onAccept }) => {
    const [isAccepting, setIsAccepting] = useState(false);

    const handleAccept = async () => {
        setIsAccepting(true);
        await onAccept();
        setIsAccepting(false); // Likely unmounted by parent before this runs, but safe.
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-80 backdrop-blur-sm p-4">
            <div className="bg-gray-900 border border-purple-500 rounded-lg shadow-2xl max-w-lg w-full overflow-hidden flex flex-col max-h-[90vh]">
                {/* Header */}
                <div className="p-6 border-b border-gray-700 bg-gray-800">
                    <h2 className="text-2xl font-bold text-white mb-1">Terms of Service</h2>
                    <p className="text-gray-400 text-sm">Please review and accept our terms to continue.</p>
                </div>

                {/* Scrollable Content */}
                <div className="p-6 overflow-y-auto text-gray-300 text-sm leading-relaxed space-y-4">
                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">1. AI Disclaimer</h3>
                        <p>
                            This application uses Artificial Intelligence to generate content. The AI may inadvertently produce inaccurate, misleading, or offensive material. The views and content generated by the AI do not reflect the views of the developer.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">2. Liability</h3>
                        <p>
                            You accept full responsibility for any content you generate or share using this tool. The developer provides this service "as is" and is not liable for any damages arising from its use.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">3. Privacy & Data</h3>
                        <p className="mb-2">
                            Your conversations and generated content are stored and may be reviewed.
                        </p>
                        <p className="text-red-400 font-semibold text-xs uppercase tracking-wide">
                            ⚠️ Warning: Do not share any personal information in your chats.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">4. Age Requirement</h3>
                        <p>
                            You confirm that you are at least 18 years of age (or of legal age in your jurisdiction) to use this application.
                        </p>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-gray-700 bg-gray-800 flex justify-end">
                    <button
                        onClick={handleAccept}
                        disabled={isAccepting}
                        className={`
                            px-6 py-3 rounded-md font-bold text-white shadow-lg transition-all
                            ${isAccepting
                                ? 'bg-gray-600 cursor-not-allowed'
                                : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 hover:scale-105 active:scale-95'}
                        `}
                    >
                        {isAccepting ? 'Accepting...' : 'I Accept & Continue'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default LegalAgreementModal;
