import React, { useState, useEffect, useRef } from 'react';
import { collection, query, getDocs, orderBy, where, getCountFromServer, addDoc, serverTimestamp } from 'firebase/firestore';
import { signInWithPopup } from 'firebase/auth';
import { db, auth, googleProvider } from './firebaseConfig';
import { Users, DollarSign, Image, UserCircle, ArrowLeft, Eye, Loader2, Volume2, UserPlus, MessageSquare, X, Send, Coins } from 'lucide-react';
import { formatDistanceToNow, format, isWithinInterval, subHours } from 'date-fns';
import { getCredits, addCredits } from './services';

// --- Custom Hooks ---

/**
 * Custom hook to handle ESC key press
 * @param {Function} onEscape - Callback function to execute when ESC is pressed
 * @param {boolean} enabled - Whether the hook is enabled (default: true)
 */
export const useEscapeKey = (onEscape, enabled = true) => {
    useEffect(() => {
        if (!enabled || !onEscape) return;

        const handleEscape = (e) => {
            if (e.key === 'Escape') {
                onEscape();
            }
        };

        window.addEventListener('keydown', handleEscape);
        return () => window.removeEventListener('keydown', handleEscape);
    }, [onEscape, enabled]);
};

// --- Login Component ---
export const Login = () => {
    const handleGoogleSignIn = async () => {
        try {
            await signInWithPopup(auth, googleProvider);
        } catch (error) {
            console.error("Error signing in with Google", error);
        }
    };

    return (
        <div className="flex flex-col items-center justify-center h-screen bg-gray-900 text-white">
            <h1 className="text-4xl font-bold mb-8 text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
                NPC Assistant
            </h1>
            <button
                onClick={handleGoogleSignIn}
                className="px-6 py-3 bg-white text-gray-900 font-semibold rounded-lg shadow-md hover:bg-gray-100 transition duration-300 flex items-center gap-2"
            >
                <img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="Google G" className="w-6 h-6" />
                Sign in with Google
            </button>
        </div>
    );
};

// --- LegalAgreementModal Component ---
export const LegalAgreementModal = ({ onAccept }) => {
    const [isAccepting, setIsAccepting] = useState(false);

    const handleAccept = async () => {
        setIsAccepting(true);
        await onAccept();
        setIsAccepting(false); // Likely unmounted by parent before this runs, but safe.
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-80 backdrop-blur-sm p-4">
            <div className="bg-gray-900 border border-purple-500 rounded-lg shadow-2xl max-w-lg w-full overflow-hidden flex flex-col max-h-[90vh]">
                {/* Header */}
                <div className="p-6 border-b border-gray-700 bg-gray-800">
                    <h2 className="text-2xl font-bold text-white mb-1">Terms of Service</h2>
                    <p className="text-gray-400 text-sm">Please review and accept our terms to continue.</p>
                </div>

                {/* Scrollable Content */}
                <div className="p-6 overflow-y-auto text-gray-300 text-sm leading-relaxed space-y-4">
                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">1. AI Disclaimer</h3>
                        <p>
                            This application uses Artificial Intelligence to generate content. The AI may inadvertently produce inaccurate, misleading, or offensive material. The views and content generated by the AI do not reflect the views of the developer.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">2. Liability</h3>
                        <p>
                            You accept full responsibility for any content you generate or share using this tool. The developer provides this service "as is" and is not liable for any damages arising from its use.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">3. Privacy & Data</h3>
                        <p className="mb-2">
                            Your conversations and generated content are stored and may be reviewed.
                        </p>
                        <p className="text-red-400 font-semibold text-xs uppercase tracking-wide">
                            ⚠️ Warning: Do not share any personal information in your chats.
                        </p>
                    </div>

                    <div className="bg-gray-800 p-4 rounded border border-gray-700">
                        <h3 className="text-white font-semibold mb-2">4. Age Requirement</h3>
                        <p>
                            You confirm that you are at least 18 years of age (or of legal age in your jurisdiction) to use this application.
                        </p>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-gray-700 bg-gray-800 flex justify-end">
                    <button
                        onClick={handleAccept}
                        disabled={isAccepting}
                        className={`
                            px-6 py-3 rounded-md font-bold text-white shadow-lg transition-all
                            ${isAccepting
                                ? 'bg-gray-600 cursor-not-allowed'
                                : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 hover:scale-105 active:scale-95'}
                        `}
                    >
                        {isAccepting ? 'Accepting...' : 'I Accept & Continue'}
                    </button>
                </div>
            </div>
        </div>
    );
};

// --- FeedbackButton Component ---
export const FeedbackButton = () => {
    const [isOpen, setIsOpen] = useState(false);
    const [feedback, setFeedback] = useState('');
    const [submitted, setSubmitted] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);

    const handleSubmit = async () => {
        if (!feedback.trim() || isSubmitting) return;

        setIsSubmitting(true);
        try {
            await addDoc(collection(db, 'feedback'), {
                userId: auth.currentUser?.uid,
                email: auth.currentUser?.email,
                message: feedback,
                timestamp: serverTimestamp()
            });

            setSubmitted(true);
            setTimeout(() => {
                setIsOpen(false);
                setSubmitted(false);
                setFeedback('');
            }, 2000);
        } catch (error) {
            console.error('Error submitting feedback:', error);
            alert('Failed to submit feedback. Please try again.');
        } finally {
            setIsSubmitting(false);
        }
    };

    // ESC key handler
    useEscapeKey(() => setIsOpen(false), isOpen);

    const handleKeyDown = (e) => {
        if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
            handleSubmit();
        }
    };

    return (
        <>
            <button
                onClick={() => setIsOpen(true)}
                className="w-full mt-4 flex items-center justify-center px-4 py-2 text-sm text-indigo-600 bg-indigo-50 rounded-lg hover:bg-indigo-100 transition-colors"
                title="Send feedback or report issues"
            >
                <MessageSquare className="w-4 h-4 mr-2" />
                Send Feedback
            </button>

            {isOpen && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" onClick={() => setIsOpen(false)}>
                    <div className="bg-white rounded-lg p-6 max-w-md w-full shadow-xl" onClick={e => e.stopPropagation()}>
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-xl font-bold text-gray-900">Send Feedback</h3>
                            <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-gray-600">
                                <X className="w-6 h-6" />
                            </button>
                        </div>

                        {submitted ? (
                            <div className="text-center py-8">
                                <div className="text-green-600 text-lg font-semibold mb-2">✓ Thank you!</div>
                                <p className="text-gray-600">Your feedback has been received.</p>
                            </div>
                        ) : (
                            <>
                                <textarea
                                    value={feedback}
                                    onChange={(e) => setFeedback(e.target.value)}
                                    onKeyDown={handleKeyDown}
                                    placeholder="Share your thoughts, report bugs, or request features..."
                                    className="w-full p-3 border border-gray-300 rounded-lg mb-4 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 resize-none"
                                    rows={5}
                                    autoFocus
                                    disabled={isSubmitting}
                                />
                                <div className="flex justify-between items-center">
                                    <p className="text-xs text-gray-500">Press Cmd+Enter to submit</p>
                                    <button
                                        onClick={handleSubmit}
                                        disabled={!feedback.trim() || isSubmitting}
                                        className="flex items-center px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                                    >
                                        {isSubmitting ? (
                                            <>Sending...</>
                                        ) : (
                                            <>
                                                <Send className="w-4 h-4 mr-2" />
                                                Submit
                                            </>
                                        )}
                                    </button>
                                </div>
                            </>
                        )}
                    </div>
                </div>
            )}
        </>
    );
};

// --- GoldStoreModal Component ---
export const GoldStoreModal = ({ userId, onClose }) => {
    const [credits, setCredits] = useState(0);
    const [loading, setLoading] = useState(true);
    const [buying, setBuying] = useState(false);

    useEffect(() => {
        loadCredits();
    }, [userId]);

    // ESC key handler
    useEscapeKey(onClose);

    const loadCredits = async () => {
        setLoading(true);
        const amount = await getCredits(userId);
        setCredits(amount);
        setLoading(false);
    };

    const handleBuyGold = async () => {
        setBuying(true);
        try {
            const newBalance = await addCredits(userId, 25);
            setCredits(newBalance);
        } catch (error) {
            console.error("Failed to add credits", error);
        } finally {
            setBuying(false);
        }
    };

    return (
        <div
            className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4"
            onClick={onClose}
        >
            <div
                className="bg-gray-800 border border-yellow-600 rounded-xl shadow-2xl max-w-sm w-full p-6 relative overflow-hidden"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Decorative background glow */}
                <div className="absolute top-0 right-0 -mt-8 -mr-8 w-32 h-32 bg-yellow-500 rounded-full mix-blend-overlay filter blur-3xl opacity-20"></div>

                <h2 className="text-3xl font-bold text-yellow-400 mb-6 text-center" style={{ textShadow: '0 2px 4px rgba(0,0,0,0.5)' }}>Gold Store</h2>

                <div className="bg-gray-900 rounded-lg p-6 mb-6 text-center border border-gray-700">
                    <p className="text-gray-400 text-sm uppercase tracking-wider mb-1">Current Balance</p>
                    <div className="text-5xl font-extrabold text-white flex items-center justify-center gap-2">
                        {loading ? (
                            <span className="animate-pulse">...</span>
                        ) : (
                            <>
                                <>
                                    <>
                                        <Coins className="w-12 h-12 text-yellow-600 fill-yellow-400" /> <span className="text-white">{credits}</span>
                                    </>
                                </>
                            </>
                        )}
                    </div>
                </div>

                <div className="space-y-3 mb-8">
                    <h3 className="text-white font-semibold border-b border-gray-700 pb-2">Price List</h3>
                    <div className="flex justify-between items-center text-gray-300">
                        <span>Generare NPC</span>
                        <span className="text-yellow-400 font-mono">1 Gold</span>
                    </div>
                    <div className="flex justify-between items-center text-gray-300">
                        <span>Audio Output</span>
                        <span className="text-yellow-400 font-mono">2 Gold</span>
                    </div>
                    <div className="flex justify-between items-center text-gray-300">
                        <span>Picture Generation</span>
                        <span className="text-yellow-400 font-mono">5 Gold</span>
                    </div>
                </div>

                <button
                    onClick={handleBuyGold}
                    disabled={buying || loading}
                    className="w-full py-3 px-4 bg-gradient-to-r from-yellow-600 to-yellow-500 hover:from-yellow-500 hover:to-yellow-400 text-black font-bold rounded-lg shadow-lg transform transition hover:-translate-y-0.5 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                    {buying ? (
                        <>Adding...</>
                    ) : (
                        <>Get more Gold! <span className="text-xs bg-black bg-opacity-20 px-2 py-0.5 rounded-full text-yellow-900">+25</span></>
                    )}
                </button>

                <button
                    onClick={onClose}
                    className="absolute top-2 right-2 text-gray-500 hover:text-white p-2"
                    aria-label="Close"
                >
                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    );
};

// --- AdminDashboard Component ---
// Stat Card Component
const StatCard = ({ icon: Icon, label, value, color }) => {
    const colorClasses = {
        blue: 'bg-blue-100 text-blue-600',
        purple: 'bg-purple-100 text-purple-600',
        green: 'bg-green-100 text-green-600',
        red: 'bg-red-100 text-red-600',
        indigo: 'bg-indigo-100 text-indigo-600'
    };

    return (
        <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
                <div>
                    <p className="text-sm font-medium text-gray-600">{label}</p>
                    <p className="text-2xl font-bold text-gray-900 mt-2">{value}</p>
                </div>
                <div className={`p-3 rounded-lg ${colorClasses[color]}`}>
                    <Icon className="w-6 h-6" />
                </div>
            </div>
        </div>
    );
};

export const AdminDashboard = ({ user, onExit, onImpersonate }) => {
    const [users, setUsers] = useState([]);
    const [usageLogs, setUsageLogs] = useState([]);
    const [feedback, setFeedback] = useState([]);
    const [loading, setLoading] = useState(true);
    // eslint-disable-next-line no-unused-vars
    const [selectedUser, setSelectedUser] = useState(null);

    // Check if current user is admin
    const isAdmin = user?.email === import.meta.env.VITE_ADMIN_EMAIL;

    useEffect(() => {
        if (!isAdmin) return;
        loadAdminData();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isAdmin]);

    const loadAdminData = async () => {
        setLoading(true);
        try {
            // Load all users
            const usersSnapshot = await getDocs(collection(db, 'all_users'));

            // Fetch NPC counts for each user
            const usersDataPromises = usersSnapshot.docs.map(async doc => {
                const userData = doc.data();
                const userId = doc.id;

                let npcCount = 0;
                try {
                    const npcsColl = collection(db, `users/${userId}/npcs`);
                    const snapshot = await getCountFromServer(npcsColl);
                    npcCount = snapshot.data().count;
                } catch (e) {
                    console.warn(`Could not fetch NPC count for user ${userId}`, e);
                }

                return {
                    id: userId,
                    ...userData,
                    npcCount
                };
            });

            const usersData = await Promise.all(usersDataPromises);

            // Load all usage logs
            const logsSnapshot = await getDocs(
                query(collection(db, 'usage_logs'), orderBy('timestamp', 'desc'))
            );
            const logsData = logsSnapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            }));

            // Load all feedback
            const feedbackSnapshot = await getDocs(
                query(collection(db, 'feedback'), orderBy('timestamp', 'desc'))
            );
            const feedbackData = feedbackSnapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            }));

            setUsers(usersData);
            setUsageLogs(logsData);
            setFeedback(feedbackData);
        } catch (error) {
            console.error('Error loading admin data:', error);
        } finally {
            setLoading(false);
        }
    };

    // Calculate stats per user
    const getUserStats = (userId) => {
        const userLogs = usageLogs.filter(log => log.userId === userId);
        const dalleCount = userLogs.filter(log => log.type === 'dalle').length;
        const geminiTTSCount = userLogs.filter(log => log.type === 'gemini_tts').length;
        const elevenLabsTTSCount = userLogs.filter(log => log.type === 'elevenlabs_tts').length;
        const chatCount = userLogs.filter(log => log.type === 'gemini_chat').length;
        const totalCost = userLogs.reduce((sum, log) => sum + (log.estimatedCost || 0), 0);

        return {
            dalleCount,
            geminiTTSCount,
            elevenLabsTTSCount,
            chatCount,
            totalCost: totalCost.toFixed(2)
        };
    };

    // Calculate overall stats
    const totalActiveNPCs = users.reduce((sum, user) => sum + (user.npcCount || 0), 0);
    const totalNPCsCreated = usageLogs.filter(log => log.type === 'npc_created').length;

    const overallStats = {
        totalUsers: users.length,
        totalActiveNPCs,
        totalNPCsCreated,
        totalDalleImages: usageLogs.filter(log => log.type === 'dalle').length,
        totalTTSCalls: usageLogs.filter(log => log.type === 'gemini_tts' || log.type === 'elevenlabs_tts').length,
        totalCost: usageLogs.reduce((sum, log) => sum + (log.estimatedCost || 0), 0).toFixed(2),
        totalFeedback: feedback.length
    };

    // Format last seen timestamp
    const formatLastSeen = (lastSeenTimestamp) => {
        if (!lastSeenTimestamp?.toDate) {
            return { display: 'N/A', tooltip: 'Never seen' };
        }

        try {
            const date = lastSeenTimestamp.toDate();
            const fullTimestamp = format(date, 'MMM d, yyyy HH:mm');
            const now = new Date();
            const twelveHoursAgo = subHours(now, 12);

            // If within last 12 hours, show relative time with full timestamp as tooltip
            if (isWithinInterval(date, { start: twelveHoursAgo, end: now })) {
                const relativeTime = formatDistanceToNow(date, { addSuffix: true });
                return { display: relativeTime, tooltip: fullTimestamp };
            }

            // Otherwise show full date and time
            return { display: fullTimestamp, tooltip: fullTimestamp };
        } catch (error) {
            // Fallback if any date formatting fails
            console.warn('Error formatting last seen:', error);
            try {
                const date = lastSeenTimestamp.toDate();
                const fallback = format(date, 'MMM d, yyyy HH:mm');
                return { display: fallback, tooltip: fallback };
            } catch {
                return { display: 'N/A', tooltip: 'Invalid date' };
            }
        }
    };

    if (!isAdmin) {
        return (
            <div className="flex items-center justify-center h-screen bg-gray-100">
                <div className="text-center p-8 bg-white rounded-lg shadow-lg">
                    <h2 className="text-2xl font-bold text-red-600 mb-4">Access Denied</h2>
                    <p className="text-gray-600">You do not have admin privileges.</p>
                </div>
            </div>
        );
    }

    if (loading) {
        return (
            <div className="flex items-center justify-center h-screen bg-gray-100">
                <Loader2 className="w-12 h-12 animate-spin text-indigo-600" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-100 p-8">
            <div className="max-w-7xl mx-auto">
                {/* Header */}
                <div className="flex items-center justify-between mb-8">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">Admin Dashboard</h1>
                        <p className="text-gray-600 mt-1">Monitor users, usage, and costs</p>
                    </div>
                    <button
                        onClick={onExit}
                        className="flex items-center px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to App
                    </button>
                </div>

                {/* Summary Cards */}
                <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-6 mb-8">
                    <StatCard
                        icon={Users}
                        label="Total Users"
                        value={overallStats.totalUsers}
                        color="blue"
                    />
                    <StatCard
                        icon={UserCircle}
                        label="Active NPCs"
                        value={overallStats.totalActiveNPCs}
                        color="green"
                    />
                    <StatCard
                        icon={UserPlus}
                        label="NPCs Created"
                        value={overallStats.totalNPCsCreated}
                        color="indigo"
                    />
                    <StatCard
                        icon={Image}
                        label="DALL-E Images"
                        value={overallStats.totalDalleImages}
                        color="purple"
                    />
                    <StatCard
                        icon={Volume2}
                        label="TTS Calls"
                        value={overallStats.totalTTSCalls}
                        color="green"
                    />
                    <StatCard
                        icon={DollarSign}
                        label="Total Cost"
                        value={`$${overallStats.totalCost}`}
                        color="red"
                    />
                </div>

                {/* Users Table */}
                <div className="bg-white rounded-lg shadow-lg overflow-hidden mb-8">
                    <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
                        <h2 className="text-xl font-bold text-gray-900">Users</h2>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-gray-50 border-b border-gray-200">
                                <tr>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Active NPCs
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Images
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        TTS Calls
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Messages
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Total Cost
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Last Seen
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Actions
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-200">
                                {users.map(userData => {
                                    const stats = getUserStats(userData.id);
                                    return (
                                        <tr key={userData.id} className="hover:bg-gray-50">
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                                {userData.email}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                {userData.npcCount || 0}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                {stats.dalleCount}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                {stats.geminiTTSCount + stats.elevenLabsTTSCount}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                {stats.chatCount}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                                                ${stats.totalCost}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600" title={formatLastSeen(userData.lastSeen).tooltip}>
                                                {formatLastSeen(userData.lastSeen).display}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm">
                                                <button
                                                    onClick={() => onImpersonate(userData.id, userData.email)}
                                                    className="flex items-center px-3 py-1 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition-colors"
                                                >
                                                    <Eye className="w-4 h-4 mr-1" />
                                                    View as User
                                                </button>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* Feedback Section */}
                {feedback.length > 0 && (
                    <div className="bg-white rounded-lg shadow-lg overflow-hidden">
                        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
                            <h2 className="text-xl font-bold text-gray-900">User Feedback</h2>
                        </div>
                        <div className="divide-y divide-gray-200">
                            {feedback.slice(0, 10).map(item => (
                                <div key={item.id} className="px-6 py-4">
                                    <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                            <p className="text-sm font-medium text-gray-900">{item.email}</p>
                                            <p className="text-sm text-gray-600 mt-1">{item.message}</p>
                                        </div>
                                        <span className="text-xs text-gray-500 ml-4">
                                            {item.timestamp?.toDate ? new Date(item.timestamp.toDate()).toLocaleDateString() : 'N/A'}
                                        </span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};
